[package]
name = "assembly_emulator"
version = "0.1.0"
authors = ["KevinCybura <KevinCybura@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
